import { useEffect, useState } from 'react'
import { useParams, useLocation, useNavigate } from 'react-router-dom'
import Layout from '../components/Layout'
import { getLoanApplication } from '../services/api'
import { MdCheckCircle, MdCancel, MdFileDownload, MdRefresh, MdHistory } from 'react-icons/md'
import jsPDF from 'jspdf'

export default function PredictionResultPage() {
  const { applicationId } = useParams()
  const { state } = useLocation()
  const navigate = useNavigate()
  const [result, setResult] = useState(state?.predictionResult || null)
  const [appData, setAppData] = useState(state?.applicationData || null)
  const [loading, setLoading] = useState(!result)

  useEffect(() => {
    if (!result) {
      getLoanApplication(applicationId)
        .then(res => {
          const a = res.data.application
          setAppData(a)
          setResult({
            status: a.status,
            eligible: a.status === 'Eligible',
            probability: a.prediction_probability ? a.prediction_probability * 100 : 0,
            suggestions: Array.isArray(a.suggestions) ? a.suggestions : []
          })
        })
        .catch(() => {})
        .finally(() => setLoading(false))
    }
  }, [applicationId, result])

  const downloadPDF = () => {
    const doc = new jsPDF()
    const eligible = result?.eligible
    doc.setFillColor(eligible ? 6 : 127, eligible ? 78 : 29, eligible ? 59 : 29)
    doc.rect(0, 0, 210, 40, 'F')
    doc.setTextColor(255, 255, 255)
    doc.setFontSize(20)
    doc.setFont('helvetica', 'bold')
    doc.text('LoanWise AI — Loan Eligibility Report', 14, 20)
    doc.setFontSize(11)
    doc.text(`Application ID: #${applicationId}   Date: ${new Date().toLocaleDateString('en-IN')}`, 14, 32)

    doc.setTextColor(0, 0, 0)
    doc.setFontSize(16)
    doc.setFont('helvetica', 'bold')
    doc.text(`Status: ${result?.status || 'N/A'}`, 14, 55)
    doc.setFontSize(13)
    doc.setFont('helvetica', 'normal')
    doc.text(`Eligibility Probability: ${result?.probability?.toFixed(1)}%`, 14, 66)

    if (appData) {
      doc.setFontSize(14); doc.setFont('helvetica', 'bold')
      doc.text('Applicant Details', 14, 82)
      doc.setFont('helvetica', 'normal'); doc.setFontSize(11)
      const details = [
        ['Name', appData.full_name || appData.name], ['Loan Type', appData.loan_type],
        ['Loan Amount', `₹${Number(appData.loan_amount || 0).toLocaleString()}`],
        ['Income', `₹${Number(appData.applicant_income || 0).toLocaleString()}/month`],
        ['CIBIL Score', appData.cibil_score], ['Education', appData.education],
      ]
      details.forEach(([k, v], i) => {
        doc.text(`${k}: ${v || 'N/A'}`, 14, 92 + i * 9)
      })
    }

    if (result?.suggestions?.length) {
      doc.setFontSize(14); doc.setFont('helvetica', 'bold')
      doc.text('Improvement Suggestions', 14, 160)
      doc.setFont('helvetica', 'normal'); doc.setFontSize(10)
      result.suggestions.forEach((s, i) => {
        const clean = s.replace(/✦\s*/, '')
        doc.text(`• ${clean}`, 14, 170 + i * 8, { maxWidth: 180 })
      })
    }

    doc.setFontSize(9); doc.setTextColor(150)
    doc.text('Generated by LoanWise AI — For informational purposes only.', 14, 285)
    doc.save(`loan-eligibility-report-${applicationId}.pdf`)
  }

  if (loading) return (
    <Layout title="Prediction Result">
      <div style={{ display: 'flex', justifyContent: 'center', padding: 80 }}>
        <div className="loading-card">
          <div className="spinner" />
          <p>Loading your result...</p>
        </div>
      </div>
    </Layout>
  )

  const eligible = result?.eligible
  const probability = result?.probability || 0
  const suggestions = result?.suggestions || []

  // SVG Ring
  const r = 52, circ = 2 * Math.PI * r
  const dash = (probability / 100) * circ

  return (
    <Layout title="Prediction Result">
      <div className="fade-in" style={{ maxWidth: 820, margin: '0 auto' }}>

        {/* Main Result Card */}
        <div className={eligible ? 'result-eligible' : 'result-not-eligible'} style={{ marginBottom: 24 }}>
          <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center' }}>
            <div style={{ marginBottom: 16 }}>
              {eligible
                ? <MdCheckCircle style={{ fontSize: 72, color: '#6ee7b7' }} />
                : <MdCancel style={{ fontSize: 72, color: '#fca5a5' }} />}
            </div>

            <div className="result-status">{result?.status || 'N/A'}</div>
            <div className="result-prob">Application #{applicationId}</div>

            {/* Probability Ring */}
            <div className="prob-ring" style={{ margin: '24px auto 8px' }}>
              <svg viewBox="0 0 120 120" width="130" height="130">
                <circle cx="60" cy="60" r={r} fill="none" stroke="rgba(255,255,255,0.15)" strokeWidth="10" />
                <circle
                  cx="60" cy="60" r={r} fill="none"
                  stroke={eligible ? '#6ee7b7' : '#fca5a5'}
                  strokeWidth="10"
                  strokeDasharray={`${dash} ${circ}`}
                  strokeLinecap="round"
                />
              </svg>
              <div className="prob-ring-text">{probability.toFixed(0)}%</div>
            </div>

            <p style={{ opacity: 0.8, fontSize: 15 }}>Eligibility Confidence Score</p>
          </div>
        </div>

        <div className="grid-2" style={{ marginBottom: 24 }}>
          {/* Application Summary */}
          {appData && (
            <div className="card card-body">
              <div style={{ fontSize: 16, fontWeight: 700, color: 'var(--navy)', marginBottom: 16 }}>📋 Application Details</div>
              <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
                {[
                  ['Loan Type', appData.loan_type],
                  ['Applicant', appData.full_name],
                  ['Loan Amount', `₹${Number(appData.loan_amount || 0).toLocaleString()}`],
                  ['Monthly Income', `₹${Number(appData.applicant_income || 0).toLocaleString()}`],
                  ['Co-app Income', `₹${Number(appData.coapplicant_income || 0).toLocaleString()}`],
                  ['CIBIL Score', appData.cibil_score],
                  ['Education', appData.education],
                  ['Property Area', appData.property_area],
                ].map(([k, v]) => (
                  <div key={k} style={{ display: 'flex', justifyContent: 'space-between', fontSize: 13, borderBottom: '1px solid var(--gray-100)', paddingBottom: 8 }}>
                    <span style={{ color: 'var(--gray-500)' }}>{k}</span>
                    <span style={{ fontWeight: 600, color: 'var(--navy)' }}>{v || '—'}</span>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Suggestions */}
          <div className="card card-body">
            <div style={{ fontSize: 16, fontWeight: 700, color: 'var(--navy)', marginBottom: 16 }}>
              💡 {eligible ? 'Tips to Stay Eligible' : 'How to Improve Eligibility'}
            </div>
            {suggestions.length > 0 ? (
              <ul className="suggestion-list">
                {suggestions.map((s, i) => (
                  <li key={i}>{s}</li>
                ))}
              </ul>
            ) : (
              <div style={{ color: 'var(--gray-500)', fontSize: 14 }}>
                {eligible
                  ? '✅ Your profile is strong! Maintain your credit score and income.'
                  : 'No specific suggestions available. Please review your application details.'}
              </div>
            )}

            {!eligible && (
              <div className="alert alert-warning" style={{ marginTop: 16, fontSize: 13 }}>
                ⚠️ This is an AI-generated prediction for informational purposes. Final approval is subject to bank's discretion.
              </div>
            )}
          </div>
        </div>

        {/* Actions */}
        <div style={{ display: 'flex', gap: 12, flexWrap: 'wrap', justifyContent: 'flex-end' }}>
          <button className="btn btn-ghost" onClick={() => navigate('/history')}>
            <MdHistory /> View All History
          </button>
          <button className="btn btn-outline" onClick={() => navigate('/loan-category')}>
            <MdRefresh /> New Application
          </button>
          <button className="btn btn-primary" onClick={downloadPDF}>
            <MdFileDownload /> Download PDF Report
          </button>
        </div>
      </div>
    </Layout>
  )
}
